# Rust
- id: rust-fmt
  name: fmt
  description: Format files with cargo fmt.
  entry: cargo fmt
  language: system
  types: [rust]
  args: ["--"]
- id: rust-check
  name: cargo check
  description: Check the package for errors.
  entry: cargo check
  language: system
  types: [rust]
  pass_filenames: false
- id: rust-clippy
  name: clippy
  description: Lint rust sources
  entry: cargo clippy
  language: system
  args: ["--", "-D", "warnings"]
  types: [rust]
  pass_filenames: false
- id: rust-test
  name: cargo test
  description: Run the project test suite
  entry: cargo test
  language: system
  types: [rust]
  pass_filenames: false
# PHP
- id: php-cs-fixer
  name: PHP CS-Fixer
  description: Fix PHP Code Standard
  entry: vendor/bin/php-cs-fixer fix
  language: system
  types: [php]
  pass_filenames: true
- id: php-stan
  name: PHP Stan
  description: PHP Static Analysis
  entry: vendor/bin/phpstan analyse
  language: system
  types: [php]
  pass_filenames: true
# Nix
- id: nix-nixpkgs-fmt
  name: nixpkgs-fmt
  description: Format nix package with nixpkgs-fmt
  entry: nixpkgs-fmt --check --explain
  language: system
  types: [nix]
  pass_filenames: true
- id: nix-nixfmt
  name: nixfmt
  description: Format nix package with nixfmt
  entry: nixfmt --check
  language: system
  types: [nix]
  pass_filenames: true
- id: nix-alejandra
  name: alejandra
  description: Format nix package with alejandra
  entry: alejandra --check
  language: system
  types: [nix]
  pass_filenames: true
# JavaScript/TypeScript
- id: js-prettier
  name: js-prettier
  description: "Format JavaScript/TypeScript files with prettier"
  entry: prettier --write --list-different --ignore-unknown
  language: node
  types_or: [javascript, jsx, ts, tsx]
  args: []
  require_serial: false
  additional_dependencies: ["prettier@latest"]
  minimum_pre_commit_version: "0"
